[package]
name = "non-blank-string-rs"
version = "1.0.1"
edition = "2021"

[features]
default = []
utils = []

[dependencies]
serde = { version = "1", features = ["derive"] }

fake = "2"

[dev-dependencies]
serde_json = "1.0.82"
