[package]
name = "non-blank-string-rs"
version = "1.0.0"
edition = "2021"

[dependencies]
thiserror = "1.0.31"

serde = { version = "1", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0.82"